
##
# Ansible playbook for additional contrail packages needed on server on Ubuntu 12.04.3 LTS.
#


- hosts: contrail 
  user: root
  tasks:
    ##
    # Apt package installation of required software.
    #
    - name: Install required public repository packages.
      action: apt pkg={{ item }} state=present
      with_items:
        - cdbs                   # (>= 0.4.90~) 
        - libncurses5-dev 
        - libreadline-dev 
        - python-all-dev         # (>= 2.6.6-3~) 
        - libavahi-client-dev 
        - libsasl2-dev 
        - libxen-dev 
        - open-iscsi-utils 
        - libparted0-dev         # (>= 2.2) 
        - libdevmapper-dev 
        - uuid-dev 
        - libudev-dev 
        - libpciaccess-dev 
        - libcap-ng-dev 
        - libnl-3-dev 
        - libyajl-dev 
        - libpcap0.8-dev 
        - libnuma-dev 
        - radvd 
        - libxml2-utils 
        - libapparmor-dev 
        - dnsmasq-base

    - name: paramiko install
      pip: name=paramiko version=1.11.0 state=present

    - name: Fabric install
      pip: name=fabric version=1.7.0 state=present  

