
- hosts: contrail
  user: root
  tasks:
    - selinux: state=disabled
    - lineinfile: dest=/etc/sysconfig/network regexp=^NISDOMAIN= line=NISDOMAIN=juniper.net 
     
    - apt: pkg=nis state=present
    - apt: pkg=rpcbind state=present
    - apt: pkg=ypbind state=present
    - apt: pkg=autofs state=present
    - service: name=autofs enabled=yes
    - service: name=ypbind enabled=yes
    - service: name=rpcbind enabled=yes
    - service: name=rpcbind state=started

    - name: autmaster file
      template: src=auto/auto.master dest=/etc/auto.master
      notify:
      - Restart Autofs
      
    - name: ypconf file
      template: src=auto/yp.conf dest=/etc/yp.conf
      notify:
      - Restart Ypbind

    - name: nsswitch file
      template: src=auto/nsswitch.conf dest=/etc/nsswitch.conf
      notify:
      - Restart Ypbind
      - Restart Autofs
    
    - service: name=ypbind state=started
    - service: name=autofs state=started

  handlers:
    - name: Restart Ypbind
      service: name=ypbind state=restarted

    - name: Restart Autofs
      service: name=autofs state=restarted

